name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    #- name: Build the Docker image
      #run: docker build . --file dash-deployment/Dockerfile --tag my-image-name:$(date +%s)
      
    - name: Docker-Compose Publish
  # You may pin to the exact commit or the version.
      uses: pennsignals/publish_docker-compose@v0.1.1
      with:
        # Release version (tag)
        version: '' 
        # docker-compose file to build and publish images from
        docker_compose: 'dash-deployment/docker-compose.yaml'
        # Github Repo token
        repo_token: "${{ secrets.GITHUB_TOKEN }}"

